<?php

namespace Prodotti\Entity\Repository;

/**
 * ProdottiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProdottiRepository extends \Doctrine\ORM\EntityRepository
{

    public function getListaProdotti() {

        $em = $this->getEntityManager();

        $dql = 'SELECT p, c
                FROM \Prodotti\Entity\Prodotto p
                JOIN p.categoria c
                ORDER BY p.nome';

        $query = $em->createQuery($dql);
        return $query->getResult();

    }

}
